openapi: 3.0.3


components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          example: "example@gmail.com"
        password:
          type: string
          example: "password123"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        businessName:
          type: string
          example: "BillTracka Enterprises"
      xml:
        name: "user"


  requestBodies:
    CreateUser:
      required: true
      description: "User to be created"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

  
