name: pull-to-server
on: [push]
jobs:
  pull-main-branch:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo 'hello world'
      - run: echo '${{ secrets.MAIN_BRANCH }}'
      - run: echo '${{ secrets.PRIVATE_KEY }}'
      - run: echo '${{ secrets.SSh_HOST }}'
